ALTER TABLE profiles ADD COLUMN secret_key TEXT DEFAULT NULL AFTER api_key;
ALTER TABLE payments ADD COLUMN name_pdf VARCHAR(255) DEFAULT NULL AFTER status;
/*nuevos alter*/
ALTER TABLE categories MODIFY COLUMN id_parent INTEGER DEFAULT NULL;
ALTER TABLE coupons MODIFY COLUMN id_parent INTEGER DEFAULT NULL;
ALTER TABLE profiles MODIFY COLUMN name_store VARCHAR(255) DEFAULT NULL;
ALTER TABLE profiles MODIFY COLUMN img_profile VARCHAR(255) DEFAULT NULL;
ALTER TABLE profiles MODIFY COLUMN api_key VARCHAR(255) DEFAULT NULL;
ALTER TABLE profiles MODIFY COLUMN secret_key VARCHAR(255) DEFAULT NULL;
ALTER TABLE payments ADD COLUMN id_carrier VARCHAR(255) DEFAULT NULL AFTER status;
ALTER TABLE payments ADD COLUMN amount_discount_coupons VARCHAR(255) DEFAULT NULL AFTER status;
ALTER TABLE payments ADD COLUMN flow_order_payment VARCHAR(255) DEFAULT NULL AFTER status;
ALTER TABLE coupons ADD COLUMN status TINYINT DEFAULT 1 AFTER date_expiration;
ALTER TABLE products ADD COLUMN status TINYINT DEFAULT 1 AFTER is_premium;
ALTER TABLE coupons ADD COLUMN id_store INTEGER AFTER status;
ALTER TABLE coupons MODIFY COLUMN date_expiration DATE DEFAULT NULL;

/*nuevo nuevo alter */

ALTER TABLE payments ADD COLUMN token_flow VARCHAR(255) DEFAULT NULL AFTER flow_order_payment;